name: 'Actions-Secret-Modifier'

author: HarrierPigeon

description: 'Create or update secrets in github repository'

branding:
  icon: lock
  color: gray-dark

inputs:
  name:
    description: Secret name
    required: true

  value:
    description: Secret value
    required: true

  repository:
    description: Repository name
    default: ${{ github.repository }}
    required: false

  org:
    description: Indicate is an organization repo
    required: false
  
  org-name:
    description: Organization name (should be repo owner) for org repos
    required: false

  token:
    description: Repository access token
    required: true

  visibility:
    description: For orgs only. Indicate access level all, private or selected
    required: false

  selected_repository_ids:
    description: Array of repository ids in case you set visibility as selected
    required: false

outputs:
  code:
    description: Status code

  data:
    description: Response data

runs:
  using: 'node16'
  main: 'dist/index.js'